### ISSUE TITLE
coc-references display format

### ISSUE THREAD

**Issue by AlanWarren** [fannheyward/telescope-coc.nvim#13]
Hello,

I'm moving over most of my fzf configs to use telescope, and was very happy to find your plugin.  Thanks for sharing it. 

coc-references is a feature I use very often, and I find it difficult to read with telescope-coc.nvim.  

The results pane for telescope-coc.nvim formats results in 3 columns. 
`|  line number:column  |  code snippet  |  file path  |`

I'm comparing this to coc-references with FZF  (via - antoinemadec/coc-fzf) 
`|  file path:line number:column |  code snippet. |`

From a usability perspective, the most important information in the results view is the file path.  It would be great if we could see this first instead of last.  Would it be possible to re-arrange the sorting of this data? 

It may seem like a small issue, but this information is always truncated and I find it very confusing to determine which file my references are located in.  

![Screen Shot 2021-09-10 at 1 53 23 PM](https://user-images.githubusercontent.com/294606/132904015-f863f7c5-5901-4a63-9e42-bf8cecd9207c.png)

For reference, this is FZF with coc-fzf plugin.
![Screen Shot 2021-09-10 at 1 49 29 PM](https://user-images.githubusercontent.com/294606/132904063-3ee39ba6-980f-45b0-8d78-a2e0b42fcb08.png)

I realize the orientation is horizontal in the FZF screenshot, which immediately seems like a solution here, but i would prefer to use vertical layout with Telescope. (works good for me otherwise)  Anyhow, it's a very small thing, but I appreciate your time. 

Thanks

**Comment by fannheyward** [comment]
<img width="1223" alt="截屏2021-09-14 上午11 26 47" src="https://user-images.githubusercontent.com/345274/133190148-1bd3a2f8-df98-4c61-8b0f-15d4288f1065.png">

**Comment by AlanWarren** [comment]
Looks great!  thank you!
