### ISSUE TITLE
Feature Request: Add support for coc-lists

### ISSUE THREAD

**Issue by gary-ruizhang** [fannheyward/telescope-coc.nvim#17]
Add [coc-lists](https://github.com/neoclide/coc-lists) to telescope-coc

**Comment by fannheyward** [comment]
Some sources of coc-lists, for example buffers, files etc, already supported by telescope.nvim and telescope plugins, telescope-coc.nvim will not add this.

The main goal of `telescope-coc.nvim` is adding coc.nvim LSP related sources to telescope.nvim.
