### ISSUE TITLE
Select CoC command from a list

### ISSUE THREAD

**Issue by ismaelgonval** [fannheyward/telescope-coc.nvim#19]
Is there any way to select the extension subcommands (`mru`, `references`, ...) from a list? I tried `:Telescope coc` without any luck.

I am thinking about something like the Telescope `builtin` list (`:Telescope`) or CoC list (`:CocList`). This may help to easily navigate through the CoC commands from Telescope.

Thanks for taking your time developing this great extension.

**Comment by fannheyward** [comment]
Got your point, do you know any telescope extensions support this?

**Comment by ismaelgonval** [comment]
I couldn't find any but I will keep looking. 

In any case, if this is not possible right now, we could open an issue in Telescope repository. This feature can be useful for other extensions with several subcommands (p.e. `telescope-dap`, `telescope-tmux`, ...).
