### ISSUE TITLE
Telescope coc diagnostics showing only errors

### ISSUE THREAD

**Issue by last-partizan** [fannheyward/telescope-coc.nvim#20]
Hi!

`CocList diagnostics` and `CocDiagnostics` are showing not only errors, but warning and hints. And `Telescope coc diagnistics` is showing only errors.

Looking at source code i could not understand why, as i don't see any severity filtering.

Is there a way to set minimal severity level?

**Comment by fannheyward** [comment]
Try latest telescope-coc.nvim, should be fixed already.
