### ISSUE TITLE
Implement `codeLens` or `coc-references-used` 

### ISSUE THREAD

**Issue by ellioseven** [fannheyward/telescope-coc.nvim#23]
When using `references`, I get results in Telescope that aren't very useful, such as definitions and imports. It would be useful to be able to use `<plug>(coc-codelens-action)` or `<plug>(coc-references-used)` to show more meaningful references (actually used).

**Comment by Martins3** [comment]
As far I know, https://github.com/fannheyward/telescope-coc.nvim/issues/16 implement `<plug>(coc-references-used)`
