### ISSUE TITLE
 Make entries for references configurable

### ISSUE THREAD

**Issue by gbcreation** [fannheyward/telescope-coc.nvim#32]
The entries displayed in Telescope for the `:Telescope coc references` and `:Telescope coc references_used` commands are not configurable. When the filenames are long, they are truncated and the end of the paths is not visible.

Would it be possible to configure the width of the columns?

I also tried to use the `path_display` option of Telescope this way but it doesn't work : `:Telescope coc references path_display="tail"`. The "path" column is empty.

**Comment by fannheyward** [comment]
Try `:Telescope coc references path_display={'tail'}`.

Check `:h telescope.defaults.path_display`, `path_display` must be either a function or a table.
