### ISSUE TITLE
fuzzy match support

### ISSUE THREAD

**Issue by Camouflager** [fannheyward/telescope-coc.nvim#33]
CocAction('getWorkspaceSymbols', prompt) seems to only return substr matches. This makes fuzzy match impossible in telescope. Is it possible (or a good idea) to simply get all workspace symbols and sort fuzzily from there?

**Comment by fannheyward** [comment]
`:Telescope coc workspace_symbols` supports fuzzy search.

**Comment by Camouflager** [comment]
Let me clarify a bit. Suppose I have a class named 'SomeFeatureClass' in my project. In order to search for this class, I have to type the exact substring, like 'SomeFeature' or 'FeatureClass'. I can't use a subsequence combination like 'SomFeaCla'. I have experimented a bit and it's because every keystroke invokes CocAction('getWorkspaceSymbols'), which only returns substring matches. This behaviour doen't look very fuzzy to me.

**Comment by fannheyward** [comment]
I can understand your question, but this's limited by language server.

`telescope-coc.nvim` uses coc.nvim's `getWorkspaceSymbols` feature to do this, and coc.nvim uses language server's `workspace/symbol` to do this. In my tests, sometime the fuzzy match is supported, sometime it's not.

**Comment by Camouflager** [comment]
Thanks for replying.

I still have a question though. Is it possible (or a good idea) to simply get all workspace symbols and sort fuzzily from there?
