### ISSUE TITLE
Adding `Theme` support?

### ISSUE THREAD

**Issue by gilbh** [fannheyward/telescope-coc.nvim#34]
Hi,

With some Telescope builtins I work with `theme = "ivy"' (bottom window and not popup):
https://github.com/nvim-telescope/telescope.nvim#themes

Is there a way to configure `telescope-coc` to have a theme parameter?

Thanks!
Gil

**Comment by fannheyward** [comment]
Does `:Telescope coc commands theme=ivy` work for you?

**Comment by gilbh** [comment]
Fantastic! 

How do I pass the `height=0.2` parameter?  I tried:
```
Telescope coc workspace_diagnostics theme=ivy height=0.2
```

-- but did not work (sorry, don't really know lua).

Thanks again!

**Comment by fannheyward** [comment]
```
require("telescope").setup({
  extensions = {
    coc = { theme = 'ivy' }
  },
})
```

Now `:Telescope coc commands` will use ivy theme.

**Comment by gilbh** [comment]
Thank you.

In case this is helpful, here's how `height` is passed to the ivy theme for a builtin:
```
lua require('telescope.builtin').find_files(require('telescope.themes').get_ivy({layout_config={height=0.2}}))
```

In my mind, the issue might be related to the difference in how builtins are called (with parenthesis for passing arguments) and how extensions are called (with spaces separators??). Then, of course, the implementation of the extension needs to pass the arguments ... (but, again, I do not really code in Neovim/Telescope/lua so I might be way off here). 

Thanks again!

**Comment by gilbh** [comment]
Okay, mystery solved:
```
:lua require("telescope").extensions.coc.workspace_diagnostics(require('telescope.themes').get_ivy({layout_config={height=0.2}, previewer=false}))
``` 

I took me some time to get figure out the right nested syntax, and then I found how to call an extension as a function (with arguments).

Sorry for all this verbosity, but I am so happy to be able to use coc this way!

Thanks for all the help.
