### ISSUE TITLE
getting `diagnostics` only in the active buffer?

### ISSUE THREAD

**Issue by gilbh** [fannheyward/telescope-coc.nvim#35]
This is something I did not have in `coc.nvim`:
When I run the `diagnostics` extension:
```
lua require("telescope").extensions.coc.diagnostics(require('telescope.themes').get_ivy({layout_config={height=0.2}, previewer=false}))
```
I am not getting any results even if the current active buffer has them

When I run the `workspace-diagnostics` extension:
```
lua require("telescope").extensions.coc.workspace_diagnostics(require('telescope.themes').get_ivy({layout_config={height=0.2}, previewer=false}))
```
) am getting all the results in all the buffers.

I am not sure why but it seems `diagnostics` always returns empty...

Thanks!

**Comment by fannheyward** [comment]
`:Telescope coc diagnostics` always returns current buffer's diagnostics.

**Comment by gilbh** [comment]
Thanks!

I guess something is not properly configured on my nvim. See here:
![image](https://user-images.githubusercontent.com/39532610/184978648-98a3c6be-7a90-472d-b03f-a87732ec7c16.png)
There are two warnings marked in the green circle, but the ':Telescope coc diagnostics' is empty.
