### ISSUE TITLE
Telescope coc definitions to not jump

### ISSUE THREAD

**Issue by basilgood** [fannheyward/telescope-coc.nvim#37]
Hello!
Is it possible that ```Telescope coc definitions``` does not jump directly to the first definition if there is only one but opens it in telescope?
I would like telescope-coc to open all the options in telescope and have preview otherwise I can just stay with coc.nvim and not need to install another plugin.
Thanks.

**Comment by fannheyward** [comment]
```
require("telescope").setup({
  extensions = {
    coc = {
        prefer_locations = true, -- always use Telescope locations to preview definitions/declarations/implementations etc
    }
  },
})
```
