### ISSUE TITLE
search symbol freeze vim when lsp not ready

### ISSUE THREAD

**Issue by jakara** [fannheyward/telescope-coc.nvim#48]
I have the mapping:
```
nnoremap so <cmd>Telescope coc document_symbols<cr>
```
but in some large java projects, coc take a lot time to get lsp ready,  run `elescope coc document_symbols` and telescope-coc will freeze vim at all, not any single command can work at all and I have to kill the whole terminal.
Perhaps do the search async and dont block all vim basical functions is better.

**Comment by hexh250786313** [comment]
@jakara Take a look: https://github.com/fannheyward/telescope-coc.nvim/pull/52

Could you please test the pr that could fix the freezing issue
