### ISSUE TITLE
similar as #44, preview of telescope-coc locate at head instead of center

### ISSUE THREAD

**Issue by jensenojs** [fannheyward/telescope-coc.nvim#49]
```lua
require("telescope").setup({
   extensions = {
    coc = {
        prefer_locations = true,
     }
   },
 })
 require('telescope').load_extension('coc')
```

but when i use `Telescope coc references`, preview of telescope always locate at head, while `<Plug>(coc-references)` is ok

<img width="1350" alt="image" src="https://github.com/fannheyward/telescope-coc.nvim/assets/56761542/295240db-72b0-477c-8fa1-5e77947b0cbb">

noticed that similar issue : https://github.com/fannheyward/telescope-coc.nvim/issues/44

**Comment by fannheyward** [comment]
Can't reproduce, the preview location is correct in my test.

<img width="1136" alt="image" src="https://github.com/fannheyward/telescope-coc.nvim/assets/345274/8e6fff9e-b521-4488-8184-1119f298cdc2">

**Comment by jensenojs** [comment]
I was going to try again tonight (which is now), I didn't expect your reply to be so timely and responsible, I am really sorry.i wasted your time.

I found that the problem has nothing to do with other plugins. It has something to do with the function setting of buffer_previewer_maker in my telescope. When I comment it out, everything goes right.

<img width="1139" alt="image" src="https://github.com/fannheyward/telescope-coc.nvim/assets/56761542/8df8ec21-84c4-4c81-9228-3d774b4fb414">

the problem is the opts in func preview_setting, it can be used as a reference for people with similar confusion.

```lua
-- 对预览的设置
-- Ignore files bigger than a threshold
-- and don't preview binaries
local preview_setting = function(filepath, bufnr, opts)
    -- local opts = {
    --     noremap = true, -- non-recursive
    --     silent = true -- do not show message
    -- }
    filepath = vim.fn.expand(filepath)

    local previewers = require("telescope.previewers")
    local Job = require("plenary.job")

    -- 如果是二进制, 不预览
    Job:new({
        command = "file",
        args = {"--mime-type", "-b", filepath},
        on_exit = function(j)
            local mime_type = vim.split(j:result()[1], "/")[1]
            if mime_type ~= "text" then
                -- maybe we want to write something to the buffer here
                vim.schedule(function()
                    vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, {"BINARY"})
                end)
            end
        end
    }):sync()

    -- 如果文件太大, 也不预览
    vim.loop.fs_stat(filepath, function(_, stat)
        if not stat then
            return
        end
        if stat.size > 100000 then
            return
        else
            previewers.buffer_previewer_maker(filepath, bufnr, opts)
        end
    end)
end
```
