### ISSUE TITLE
Display nothing with coc mru

### ISSUE THREAD

**Issue by kdurant** [fannheyward/telescope-coc.nvim#9]
os: win10
nvim nightly

`CocList mru` displays normally 
`Telescope coc mru` display nothing

**Comment by fannheyward** [comment]
Looks like there is something broken on Windows. Can you post some example lines from `~/AppData/Local/coc/mru`?

**Comment by kdurant** [comment]
I change coc config dir to `C:\home\.config\coc`, but  there is a `mru`  in  `~/AppData/Local/coc/` 
```
c:\home\.config\coc\mru
c:\home\.config\nvim\bundle\telescope.nvim\lua\telescope\mappings.lua
e:\study\cpp\Radar\src\wave\OnlineWaveform.cpp
c:\home\AppData\Local\coc\mru
c:\home\.cache\tmp.txt
c:\home\.config\nvim\vimscript\user_plugin.vim
c:\home\.config\nvim\vimscript\plugin_config.vim
```

**Comment by fannheyward** [comment]
Sorry I don't have a Windows to test/debug this issue. You can add `print(val, p:exists(), p:is_file(), val:sub(1, #cwd))` under line 81 https://github.com/fannheyward/telescope-coc.nvim/blob/0fad822474585b74ddb3f684487f79e1b22fab5e/lua/telescope/_extensions/coc.lua#L81

What's the output?

**Comment by kdurant** [comment]
I add `print(val, p:exists(), p:is_file(), val:sub(1, #cwd), cwd)`

![QQ截图20210611221734](https://user-images.githubusercontent.com/2704364/121701015-10ac4d80-cb03-11eb-94e7-f7a02754d683.png)

**Comment by fannheyward** [comment]
@kdurant sorry for the delay.

The problem is caused by the uppercase `cwd`. Can you test `print(vim.loop.cwd(), vim.fn.getcwd())`, are they same?

**Comment by fannheyward** [comment]
I mean the `C` drive letter, are they both uppercase ?

**Comment by kdurant** [comment]
Yes

**Comment by fannheyward** [comment]
Made a fix on master, please give it a try.

**Comment by kdurant** [comment]
It can show MRU  which is only the same path with current open file.

**Comment by fannheyward** [comment]
It's expected, same as `:CocList mru`

**Comment by kdurant** [comment]
![1](https://user-images.githubusercontent.com/2704364/122154362-6f711e80-ce97-11eb-977c-a334da913b90.png)
![2](https://user-images.githubusercontent.com/2704364/122154367-70a24b80-ce97-11eb-95fc-cf6c8d55b686.png)

**Comment by fannheyward** [comment]
Are you using `:CocList mru -A`? `mru` should only list most recently used file in current cwd, https://github.com/neoclide/coc-lists/blob/70d29c3b9598e592a6216ddefb95fbe0d57fa126/src/mru.ts#L8-L11

https://github.com/fannheyward/telescope-coc.nvim/issues/5

**Comment by kdurant** [comment]
I get the same result by using `CocList mru`  or `CocList mru -A`

**Comment by fannheyward** [comment]
Looks like there's something broken with `:CocList mru`, will look into this.
